server:
  port: 9092
  context-path: /springboot

heynas:
  author:
    name: zhangsan
    age: 28
    desc: ${heynas.author.name:Lisi} is ${heynas.author.age}

logging:
  config: classpath:config/logback.xml
  pattern:
    console:


